name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  deploy-to-aws:
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_LAMBDA_ROLE_ARN: ${{ secrets.AWS_LAMBDA_ROLE_ARN }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Write Token
      - run: |
          ${{ secrets.TOKEN_FASTAPI }} >> token.txt

      - name: Docker Build
        run: |
          docker build --platform linux/amd64 -t mlops-batch-online:main .

      - name: Docker Tag
        run: |
          docker tag mlops-batch-online:main ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/mlops-batch-online:latest

      - name: Docker Push
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/mlops-batch-online:latest

      - name: Deploy Lambda
        run: python tools/lambda_function.py